name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm
      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm build

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          # 目标仓库
          repo: async-codeper/web
          # 目标仓库分支
          target_branch: main
        env:
          # docs仓库下 setting -> secrets and variables -> actions -> new repository secrets -> key: ACCESS_TOKEN
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}